# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'MovieApp' do

  # Pods for MovieApp
  pod 'Firebase/Crashlytics'
  pod 'FirebaseFirestore'
  pod 'Alamofire'
  pod 'RxSwift'

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppUITests' do
    # Pods for testing
  end

end
