# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'MovieApp' do

  # Pods for MovieApp
  pod 'Firebase/Crashlytics'
  pod 'FirebaseFirestore'
  pod 'Alamofire'
  pod 'RxSwift'

  target 'MovieAppTests' do
    inherit! :search_paths
    pod 'Sourcery', '2.1.1'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'

          # remove code coverage
          config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
          config.build_settings['ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end
end
